"""empty message

Revision ID: badc9aba148c
Revises:
Create Date: 2019-09-30 13:24:51.907163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "badc9aba148c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Artist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("city", sa.String(length=120), nullable=False),
        sa.Column("state", sa.String(length=120), nullable=False),
        sa.Column("phone", sa.String(length=120), nullable=False),
        sa.Column("genres", sa.ARRAY(sa.String(length=120)), nullable=False),
        sa.Column("image_link", sa.String(length=500), nullable=False),
        sa.Column("facebook_link", sa.String(length=120), nullable=True),
        sa.Column("website", sa.String(length=120), nullable=True),
        sa.Column("seeking_venue", sa.Boolean(), nullable=True),
        sa.Column("seeking_description", sa.String(length=120), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Venue",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("city", sa.String(length=120), nullable=False),
        sa.Column("state", sa.String(length=120), nullable=False),
        sa.Column("address", sa.String(length=120), nullable=False),
        sa.Column("phone", sa.String(length=120), nullable=False),
        sa.Column("genres", sa.ARRAY(sa.String(length=120)), nullable=False),
        sa.Column("image_link", sa.String(length=500), nullable=False),
        sa.Column("facebook_link", sa.String(length=120), nullable=True),
        sa.Column("website", sa.String(length=120), nullable=True),
        sa.Column("seeking_talent", sa.Boolean(), nullable=True),
        sa.Column("seeking_description", sa.String(length=120), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Show",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.TIMESTAMP(), nullable=False),
        sa.Column("venue_id", sa.Integer(), nullable=False),
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["artist_id"], ["Artist.id"]),
        sa.ForeignKeyConstraint(["venue_id"], ["Venue.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Show")
    op.drop_table("Venue")
    op.drop_table("Artist")
    # ### end Alembic commands ###
